### ISSUE TITLE
Support for 64-bit Vim?

### ISSUE THREAD

**Issue by MindTooth** [kkoenig/wimproved.vim#17]
Hi,

Is there support for 64-bit?  I can for the life of me make it compile in a version suited for Vim 64-bit.

Tried various compilers, configs, etc.  Just installed Visual Studio.  But still no go.

**Comment by kkoenig** [comment]
Looking into this today

**Comment by MindTooth** [comment]
I run MSYS2, so I might have cocked about a bit.

However, I generated makefiles for Visual Studio 2015 Win64.  And open the project in Visual Studio.  From there, I were able to compile successfully.

Would be nice to also have and option to have full window size when opening Gavin, and not pure fullscreen.  An autocmd with :WToggleWindowFull or something.

Thanks!
