### ISSUE TITLE
WToggleClean graphical issues

### ISSUE THREAD

**Issue by valacar** [kkoenig/wimproved.vim#20]
I found a few graphical issues with the `WToggleClean` command when the toolbar is enabled.  Here's a screenshot on Win7 (I get similar results in Win10):

*Note: screenshots are a little blurry when viewed on Imgur.com.  After clicking the link, drag and drop the image onto the browser's URL bar and it will show a cleaner version (might need click it once to zoom in also).*

[screenshot 1](http://imgur.com/6T80NT3)

* **Top image** is before WToggleClean.  Nothing wrong here...just for comparison.
* **Middle image** is after WToggleClean has been turned on.  A four pixel wide black border along to right side and bottom edge of the text area appears, which should be white to match the default color scheme's background color.  
* **Bottom image** is after WToggleClean has been toggled off.  This turns the toolbar black, as well as the scrollbar's sizing box in the bottom right.  Also, the window size is now even smaller than the original state (top image).

When using a color scheme ([screenshot 2](http://imgur.com/YcYxm3r)) other than the default, it picks the proper background color, but there's still a four pixel wide border (notice the vim status line doesn't reach all the way to the right side).  Also, the toolbar and scrollbar sizing box have been modified to use the new background instead of restoring it to the default system colors.

Another issue can occur with part of that four pixel border not being properly re-painted ([screenshot 3](http://imgur.com/Vm5xNwT)).  Take a look at that right side four pixel border which is no longer straight. I accomplished this by using `:h` to open help, and then `:bd` to close the helper buffer. It can also appear when you `:split` a window horizontally and then remove a buffer.

**My settings to test this:**
gVim was started pretty much in its default state using the command line `gvim.exe -u H:\simple_vimrc -U NONE`.  My H:\ drive points to my home directory, which has the `simple_vimrc` file that looks like this:
```
set nocompatible
execute pathogen#infect()
filetype plugin indent on
set laststatus=2
syntax on
```
These are just basic settings, plus it runs the Pathogen plugin which loads Wimproved for me. 

Lastly, I guess I should mention, I'm running a 64-bit build of gVim version 7.4 (with patches 1-898), which I downloaded from [here](https://tuxproject.de/projects/vim/).  And wimproved.dll was compiled using mingw-w64 with `cmake -G "MinGW Makefiles" . && mingw32-make`.  If you need more info, let me know.

**Comment by kkoenig** [comment]
All these cases should be covered by tests now, thanks for the excellent repro steps.

**Comment by valacar** [comment]
Looking better, but I'm seeing some problems involving re-sizing the window.  Once you resize, the text area is shifted left 2 pixels and upward 2 pixels...which brings back the problem of the 4 pixel border along the right and bottom sides.  You can end up getting something like this (notice the bottom right corner where the status line is):

![http://imgur.com/wn1qjLt](http://imgur.com/wn1qjLt)

If you can't reproduce it for some reason, I'll give step-by-step instructions.

**Comment by kkoenig** [comment]
Yup, will track this with #25
