### ISSUE TITLE
WToggleFullscreen doesn't restore the window properly

### ISSUE THREAD

**Issue by valacar** [kkoenig/wimproved.vim#21]
When using `:WToggleFullscreen` a second time, my window isn't restored to its original size and position.  Instead, the window just fills the entire screen (with titlebar and taskbar visible), almost like it was maximized.  

I'd suggest modifying `set_fullscreen_on()` so that it remembers the window size and position before going fullscreen, and then have `set_fullscreen_off()` restore it.

If you need a  screenshot or more info, let me know.

**Comment by kkoenig** [comment]
Was tracking this with #12 but this has a much better description so will close that one.

**Comment by kkoenig** [comment]
Should be fixed in dev branch.

**Comment by valacar** [comment]
Appears to be restoring the window properly now.  Thanks for fixing it.
