### ISSUE TITLE
A request of wimproved.dll release

### ISSUE THREAD

**Issue by yanqd0** [kkoenig/wimproved.vim#22]
In **Installation**, you said:
> If you have `cmake` and **Visual Studio** installed run the following:
> ```bash
> cmake -G "NMake Makefiles" . && nmake
> ```

However, There is no such environment in my Windows.

I am not the only one probably.
So, I wish that you could release *wimproved.dll* regularly.

**Comment by tbass** [comment]
I'd also prefer to have a precompiled dll distributed along with this plugin as not everybody can install the whole environment or has access to the needed tools (e.g. company environment etc.)
